#pragma once

#include <cstdint>

enum class GAP_DataType : uint8_t {
    FLAGS                             = 0x01,
    IMCOMPLETE_LIST_UUID_16           = 0x02,
    COMPLETE_LIST_UUID_16             = 0x03,
    IMCOMPLETE_LIST_UUID_32           = 0x04,
    COMPLETE_LIST_UUID_32             = 0x05,
    IMCOMPLETE_LIST_UUID_128          = 0x06,
    COMPLETE_LIST_UUID_128            = 0x07,
    SHORT_LOCAL_NAME                  = 0x08,
    COMPLETE_LOCAL_NAME               = 0x09,
    TX_POWER_LEVEL                    = 0x0A,
    CLASS_DEVICE                      = 0x0D,
    PAIRING_HASH_C                    = 0x0E,
    PAIRING_HASH_C192                 = 0x0E,
    PAIRING_RANDOMIZER_R              = 0x0F,
    PAIRING_RANDOMIZER_R192           = 0x0F,
    DEVICE_ID                         = 0x10,
    SECURITY_TK_VALUE                 = 0x10,
    SECURITY_OUT_OF_BAND              = 0x11,
    SLAVE_CONN_INTERVAL_RANGE         = 0x12,
    LIST_SERVICE_UUID_16              = 0x14,
    LIST_SERVICE_UUID_128             = 0x15,
    SERVICE_DATA                      = 0x16,
    SERVICE_DATA_UUID_16              = 0x16,
    PUBLIC_TARGET_ADDRESS             = 0x17,
    RANDOM_TARGET_ADDRESS             = 0x18,
    APPEARANCE                        = 0x19,
    ADVERTISING_INTERVAL              = 0x1A,
    LE_DEVICE_ADDRESS                 = 0x1B,
    LE_ROLE                           = 0x1C,
    PAIRING_HASH_C256                 = 0x1D,
    PAIRING_RANDOMIZER_R256           = 0x1E,
    LIST_SERVICE_UUID_32              = 0x1F,
    SERVICE_DATA_UUID_32              = 0x20,
    SERVICE_DATA_UUID_128             = 0x21,
    LE_SECURE_CONN_CONFIRMATION_VALUE = 0x22,
    LE_SECURE_CONN_RANDOM_VALUE       = 0x23,
    URI                               = 0x24,
    INDOOR_POSITIONING                = 0x25,
    TRANSPORT_DISCOVERY_DATA          = 0x26,
    LE_SUPPORTED_FEATURES             = 0x27,
    CHANNEL_MAP_UPDATE                = 0x28,
    PB_ADV                            = 0x29,
    MESH_MESSAGE                      = 0x2A,
    MESH_BEACON                       = 0x2B,
    BIG_INFO                          = 0x2C,
    BROADCAST_CODE                    = 0x2D,
    RESOLVABLE_SET_IDENTIFIER         = 0x2E,
    ADVERTISING_INTERVAL_LONG         = 0x2F,
    INFORMATION_DATA_3D               = 0x3D,
    MANUFACTURER_DATA                 = 0xFF,
};