#ifndef __BLE_SERIAL_EXTERNAL_EVENTS__
#define __BLE_SERIAL_EXTERNAL_EVENTS__

#define STM32_ID_BLE        1000
#define STM32_ID_BLE_SERIAL 1001

#define STM32_BLE_EVT_CONNECTED    1
#define STM32_BLE_EVT_DISCONNECTED 2
#define STM32_BLE_EVT_DELIMITER    3

#endif